### ISSUE TITLE
KeyError: 'blacklist'

### ISSUE THREAD

**Issue by biofcallejas** [LankyCyril/edgecase#2]
I am running edgecase and I got the error bellow, this is my code:
`edgecase tailpuller -x genome.fasta.ecx mappings25.sorted.bam
`

```
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'blacklist'
```

Any suggestion? I am using a sorted bam file of the mapped reads against reference genome.

Many thanks!

**Comment by LankyCyril** [comment]
Hi! edgeCase expects the ECX file to have a column called "blacklist," for example like in [our hg38ext index](https://github.com/LankyCyril/edgecase/blob/master/assets/hg38ext.fa.ecx). Looks like yours might not have it?

If there's no blacklisted chromosomes in your ecx file, you can just add an extra column called "blacklist" and fill it with single dashes.

I agree though that in the general case, where there's no blacklisted reference sequences, there shouldn't be any need for that column – we'll patch it in the next release to allow for ecx's without that column

**Comment by biofcallejas** [comment]
Hi! many thanks for your fast response.
You're right, column was empty, it is running now.
